# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e4_b0smWUbOOrA8lVeCWFjcFPqV6A0rD
"""

name = input("give us your name :")
print('your name is '+ name)
age = int(input("give us your age : "))
print('your age is ' + str(age))
year = (2019-age) + 100
print('you will turn 100 year old in ' + str(year))

