# -*- coding: utf-8 -*-
"""practice 2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e4_b0smWUbOOrA8lVeCWFjcFPqV6A0rD
"""

number = int(input("give me a number to check: "))
checker = int(input("give me a number to divide by: "))

if number % 4 == 0:
    print(number, "is a multiple of 4")
elif number % 2 == 0:
    print(number, "is an even number")
else:
    print(number, "is an odd number")

if number % checker == 0:
    print(number, "divides evenly by", checker)
else:
    print(number, "does not divide evenly by", checker)

