# -*- coding: utf-8 -*-
"""practice 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e4_b0smWUbOOrA8lVeCWFjcFPqV6A0rD
"""

number = int(input('please input a number : '))
mod = number % 2
if mod == 0 :
  print('your number is even')
else:
  print('your number is odd')

